version: "3.8"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root123
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
